# -*- coding: utf-8 -*-
import scrapy
from ..items import PropertywalaRenthyderabadItem
from scrapy.selector import Selector
from scrapy.http import Request
import re
from datetime import datetime as dt
from dateutil.relativedelta import relativedelta



class PropertywalarenthyderabadSpider(scrapy.Spider):
    name = "propertywalaRentHyderabad"
    allowed_domains = ["www.propertywala.com"]
    start_urls = (
        'https://www.propertywala.com/properties/type-residential/for-rent/location-hyderabad_andhra_pradesh?page=%s' % page for page in range(1, 25)
    )
    custom_settings = {
        'DEPTH_LIMIT': 10000,
        'DOWNLOAD_DELAY': 1
    }
    item = PropertywalaRenthyderabadItem()

    def parse(self, response):
        record = Selector(response)
        data = record.xpath('//li[@class="posted"]')
        #   max_page = int(response.xpath('//*[@id="propertyList"]/div[1]/div[3]/a[6]/@href').extract_first().split('=')[1])

        for i in data:
            # Extracting the urls for each property and jump to new page of that property
            ids = i.xpath('text()').extract_first().strip().encode('ascii', 'ignore').decode('ascii').replace('ID: ',
                                                                                                              '').replace(
                '  Posted:', '')
            d = i.xpath("//article[contains(@id,'" + ids + "')]/div/ul/li[3]/span/@title").extract_first()
            name_lister = i.xpath("//article[contains(@id,'" + ids + "')]/div/ul/li[3]/span/text()").extract_first()
            if d is None:
                d = i.xpath("//article[contains(@id,'" + ids + "')]/div/ul/li[3]/a/@title").extract_first()
                name_lister = i.xpath("//article[contains(@id,'" + ids + "')]/div/ul/li[3]/a/text()").extract_first()

            if 'Owner' in d:
                d = 'Owner'
            elif 'Builder' in d:
                d = 'Builder'
            elif 'Broker' in d:
                d = 'Agent'
            else:
                d = 'Propertywala User'

            # self.item['name_lister'] = lister_name

            #  nexch_data = " nexch_data Broker" + " nme Jay Sawant"
            url = ('https://www.propertywala.com/' + i.xpath('text()').extract_first().strip().encode('ascii',
                                                                                                      'ignore').decode(
                'ascii').replace('ID: ', '').replace('  Posted:', ''))  # + nexch_data
            req = Request(url, callback=self.parse1, dont_filter=True)
            req.meta['agent'] = d
            req.meta['name'] = name_lister
            yield req

        '''if (not '?' in str(response.url)):
            next_url = 'https://www.propertywala.com/properties/type-residential_apartment_flat/for-rent/location-pune_maharashtra?page=2'
            yield Request(next_url, callback=self.parse)
        else:
            if self.maxPage > max_page:
                next_url = 'https://www.propertywala.com/properties/type-residential_apartment_flat/for-rent/location-pune_maharashtra?page=' + str(
                    self.maxPage)
                self.maxPage += 1
                yield Request(next_url, callback=self.parse)
            else:
                print("End of Pages !")'''

    def parse1(self, response):

        #  nexch_data = response[9:]  # str(response).split('nexch_data')[1]
        #  response = response[:9]   response.split(' nexch_data')[0]

        record = Selector(response)

        checkprop = response.xpath('//h2[@id="AutoGeneratedTitle"]/text()').extract_first()
        if 'plot' in checkprop.lower() or 'land' in checkprop.lower():
            pass
        else:

            self.item['Selling_price'] = '0'
            self.item['Possession'] = '0'
            self.item['Status'] = 'None'
            self.item['carpet_area'] = '0'
            self.item['management_by_landlord'] = 'None'
            self.item['areacode'] = '0'
            self.item['mobile_lister'] = 'None'
            self.item['google_place_id'] = '0'
            self.item['Launch_date'] = '0'
            self.item['age'] = '0'
            self.item['address'] = 'None'
            self.item['price_on_req'] = 'FALSE'
            self.item['Details'] = 'None'
            self.item['Monthly_Rent'] = '0'
            self.item['sublocality'] = 'None'
            self.item['price_per_sqft'] = '0'
            self.item['city'] = 'Hyderabad'
            self.item['platform'] = 'Propertywala'
            self.item['listing_by'] = response.meta['agent']  # nexch_data.split(' nme ')[0]
            self.item['name_lister'] = response.meta['name']  # nexch_data.split(' nme ')[1]

            self.item['lat'] = response.xpath('//meta[@property="og:latitude"]/@content').extract_first()

            self.item['longt'] = response.xpath('//meta[@property="og:longitude"]/@content').extract_first()

            self.item['data_id'] = response.url.split('/')[-1]

            dat = response.xpath('//li[@class="noPrint"]/time/@datetime').extract_first().replace('Z', '')

            self.item['listing_date'] = dt.strftime(dt.strptime(dat, '%Y-%m-%d %H:%M:%S'), '%m/%d/%Y %H:%M:%S')

            self.item['updated_date'] = self.item['listing_date']

            conf = response.xpath('//h2[@id="AutoGeneratedTitle"]/text()').extract_first()
            bed = re.findall('[0-9]', conf)
            if bed:
                self.item['config_type'] = bed[0] + 'BHK'
            if not bed:
                self.item['config_type'] = 'None'

            try:
                loc = response.xpath('//div[@id="PropertyDetails"]/section/header/h4/text()').extract_first().strip().split(',')[1]
                self.item['locality'] = loc  # [len(loc) - 2].strip()

                build = response.xpath('//div[@id="PropertyDetails"]/section/header/h3/text()').extract_first().strip()
                build1 = response.xpath('//div[@id="PropertyDetails"]/section/header/h4/text()').extract_first().strip()
                address = response.xpath(
                    '//div[@id="PropertyDetails"]/section/header/h4/text()').extract_first().strip()
                self.item['address'] = address
            except:
                self.item['address'] = 'Delhi'
            try:
                buildname = response.xpath('//*[@id="PropertySummary"]/header/h4/text()').extract_first().split(',')[
                    0].strip()  # re.findall('for rent in (.*)?,', conf)
            except:
                self.item['Building_name'] = 'None'

            if 'House' in conf:
                self.item['property_type'] = 'House'
                self.item['Building_name'] = 'None'
            else:
                self.item['property_type'] = 'Residential'
                if buildname is not None:
                    self.item['Building_name'] = buildname
                    if self.item['locality'] in self.item['Building_name']:
                        self.item['Building_name'] = ''.join(re.findall(' in (.*)', build))
                        if ' at ' in self.item['Building_name']:
                            self.item['Building_name'] = self.item['Building_name'].split(' at ')[0]
                        elif ',' in self.item['Building_name']:
                            self.item['Building_name'] = self.item['Building_name'].split(',')[0]
                        if self.item['Building_name'] == '':
                            self.item['Building_name'] = ''.join(re.findall(' at (.*)', build))
                            if self.item['Building_name'] == '':
                                self.item['Building_name'] = ''.join(build1.split(',')[:1]).replace(
                                    self.item['locality'], '')
                    if (self.item['city'] in self.item['Building_name']) or (
                        self.item['locality'] in self.item['Building_name']) or (
                        self.item['Building_name'] in self.item['locality']) or (' for ' in self.item['Building_name']):
                        self.item['Building_name'] = ''.join(build1.split(',')[:2]).replace(self.item['locality'], '')
                    if (self.item['Building_name'] == ' ') or (self.item['Building_name'] == ''):
                        self.item['Building_name'] = 'None'
                    try:
                        re.sub('for rent', '', buildname, flags=re.IGNORECASE)
                        re.sub('for sale', '', buildname, flags=re.IGNORECASE)
                        re.sub(' in ', '', buildname, flags=re.IGNORECASE)
                        re.sub('for boys', '', buildname, flags=re.IGNORECASE)
                        re.sub('for girls', '', buildname, flags=re.IGNORECASE)
                        re.sub('bhk', '', buildname, flags=re.IGNORECASE)
                    except:
                        pass
                else:
                    self.item['Building_name'] = 'None'

            value = response.xpath('//ul[@id="PropertyAttributes"]/li/span/text()').extract()
            if ' rent ' in conf:
                self.item['txn_type'] = 'Rent'
            elif ' sale ' in conf:
                try:
                    self.item['txn_type'] = [s.split(' ')[0] for s in value if ' Property' in s][0]
                except:
                    self.item['txn_type'] = 'Sale'
            elif 'ew' in self.item['txn_type']:
                self.item['txn_type'] = 'Sale'

            try:
                price = (response.xpath('//div[@id="PropertyPrice"]/text()').extract()[1]).strip()
                if 'equest' in price:
                    self.item['price_on_req'] = 'TRUE'
                    self.item['Selling_price'] = '0'
                    self.item['Monthly_Rent'] = '0'
                else:
                    if ',' in price:
                        price = price.replace(',', '')

                    if 'ale' in self.item['txn_type']:
                        if 'la' in price:
                            price = price.split(' la')[0]
                            if ('-' in price):
                                self.item['Selling_price'] = str(float(price.split('-')[1]) * 100000)
                            else:
                                self.item['Selling_price'] = str(float(price.strip()) * 100000)
                        elif 'crore' in price.lower():
                            price = price.split(' crore')[0]
                            if ('-' in price):
                                self.item['Selling_price'] = str(float(price.split('-')[1]) * 10000000)
                            else:
                                self.item['Selling_price'] = str(float(price.strip()) * 10000000)
                        else:
                            self.item['Selling_price'] = price.strip()
                    elif 'Rent' in self.item['txn_type']:
                        if 'la' in price:
                            price = price.split(' la')[0]
                            if '-' in price:
                                self.item['Monthly_Rent'] = str(float(price.split('-')[1]) * 100000)
                            else:
                                self.item['Monthly_Rent'] = str(float(price.split('-')[0]) * 100000)
                        elif 'crore' in price:
                            price = price.split(' crore')[0]
                            if '-' in price:
                                self.item['Monthly_Rent'] = str(float(price.split('-')[-1]) * 10000000)
                            else:
                                self.item['Monthly_Rent'] = str(float(price.split('-')[0]) * 10000000)
                        else:
                            self.item['Monthly_Rent'] = price
            except:
                print('Price Exception')

            try:
                price_square = response.xpath("//ul[@id='PropertyAttributes']/li[contains(text(),'Rate')]/span/text()").extract_first().replace(',', '')
                self.item['price_per_sqft'] = price_square
            except:
                self.item['price_per_sqft'] = '0'

            try:
                poss = [pos for pos in value if ('Immediate' in pos) or (('Within' in pos) and ('Year' in pos)) or (('Within' in pos) and ('Month' in pos))][0]
            except:
                poss = 'None'
            if 'Immediate' in poss:
                self.item['Possession'] = dt.today().strftime('%m/%d/%Y %H:%M:%S')
                self.item['Status'] = 'Ready to move'
            if (('Within' in poss) and ('Year' in poss)):
                poss1 = int(poss.replace('Within ', '').split(' Year')[0])
                self.item['Possession'] = (dt.today() + relativedelta(years=poss1)).strftime('%m/%d/%Y %H:%M:%S')
                self.item['Status'] = 'Under Construction'
            if (('Within' in poss) and ('Month' in poss)):
                poss1 = int(poss.replace('Within ', '').split(' Month')[0])
                self.item['Possession'] = (dt.today() + relativedelta(months=poss1)).strftime('%m/%d/%Y %H:%M:%S')
                self.item['Status'] = 'Under Construction'

            try:
                self.item['Bua_sqft'] = response.xpath('//span[@class="areaUnit downArrow"]/text()').extract_first().split(' ')[0]
            except:
                self.item['Bua_sqft'] = '0'

            # if 'esale' in self.item['txn_type']:
            try:
                self.item['age'] = response.xpath('//ul[@id="PropertyAttributes"]/li[contains(text(),"Age")]/span/text()').extract()
            except:
                self.item['age'] = 'None'
            if not self.item['age']:
                self.item['age'] = 'None'

            try:
                if str(self.item['Building_name']).isdigit():
                    self.item['Building_name'] = 'None'

                if len(self.item['Building_name']) < 3 or len(self.item['Building_name']) > 35:
                    self.item['Building_name'] = 'None'
            except:
                pass

            self.item['scraped_time'] = dt.now().strftime('%m/%d/%Y %H:%M:%S')

            if (((not self.item['Monthly_Rent'] == '0') and (not self.item['Bua_sqft'] == '0') and (not self.item['Building_name'] == 'None') and (not self.item['lat'] == '0')) or ((not self.item['Selling_price'] == '0') and (not self.item['Bua_sqft'] == '0') and (not self.item['Building_name'] == 'None') and (not self.item['lat'] == '0')) or ((not self.item['price_per_sqft'] == '0') and (not self.item['Bua_sqft'] == '0') and (not self.item['Building_name'] == 'None') and (not self.item['lat'] == '0'))):
                self.item['quality4'] = 1
            elif (((not self.item['price_per_sqft'] == '0') and (not self.item['Building_name'] == 'None') and (not self.item['lat'] == '0')) or ((not self.item['Selling_price'] == '0') and (not self.item['Bua_sqft'] == '0') and (not self.item['lat'] == '0')) or ((not self.item['Monthly_Rent'] == '0') and (not self.item['Bua_sqft'] == '0') and (not self.item['lat'] == '0')) or ((not self.item['Selling_price'] == '0') and (not self.item['Bua_sqft'] == '0') and (not self.item['Building_name'] == 'None')) or ((not self.item['Monthly_Rent'] == '0') and (not self.item['Bua_sqft'] == '0') and (not self.item['Building_name'] == 'None'))):
                self.item['quality4'] = 0.5
            else:
                self.item['quality4'] = 0
            if ((not self.item['Building_name'] == 'None') and (not self.item['listing_date'] == '0') and (not self.item['txn_type'] == 'None') and (not self.item['property_type'] == 'None') and ((not self.item['Selling_price'] == '0') or (not self.item['Monthly_Rent'] == '0'))):
                self.item['quality1'] = 1
            else:
                self.item['quality1'] = 0

            if ((not self.item['Launch_date'] == '0') or (not self.item['Possession'] == '0')):
                self.item['quality2'] = 1
            else:
                self.item['quality2'] = 0

            if ((not self.item['mobile_lister'] == 'None') or (not self.item['listing_by'] == 'None') or (not self.item['name_lister'] == 'None')):
                self.item['quality3'] = 1
            else:
                self.item['quality3'] = 0

            yield self.item
